In [2]:
import pandas as pd
from pathlib import Path

In [3]:
ext = Path('/home/kyo/Documents/project/prd/data/external')
inter = Path('/home/kyo/Documents/project/prd/data/intermediate')
s = 'TASua	TASuaChua	TAKem	TAPhoMai	TABo	TATrung	TAThitTrang	TAThitDo	TACa	TATom	TANgheu	TACom	TAXoi	TAHuTiu	TAMi	TABanhMi	TABap	TAMiGoi	TAXucXich	TAThitNguoi	TALapXuong	TAGioThu	TAChaBong	TAKhoBo	TADongHop	TADongLanh	TASocola	TABanh	TAChe	TAKeo	TATraiCayKho	TAKhoaiTayChien	TASnack	TAPizza	TAHamburger	TARauCuSong	TARauCuChin	TATraiCay	TAHat	TANuocCoGa	TATraSua	TACaPhe	TATraDongChai	TANuocDua	TASuaDauNanh	TANuocEp	TaSamBiDao	TANuocTangLuc	TANuocYen	TACaCao	TANguCoc	TAMatOng	ThayDoiThoiQuen'
k = s.split('	')
v = ['Int64']*64
dtype = {k:v for (k, v) in zip(s.split('	'), v)}
dtype['V1'] = 'string'

df = pd.read_csv(
    ext / 'prd_v2.0.0_Form2.csv',
    usecols = [*dtype],
    dtype = dtype,
    index_col = 'V1'
)

In [9]:
df[df.isna().any(axis=1)].sort_values(by='V1')

,TASua,TASuaChua,TAKem,TAPhoMai,TABo,TATrung,TAThitTrang,TAThitDo,TACa,TATom,...,TANuocDua,TASuaDauNanh,TANuocEp,TaSamBiDao,TANuocTangLuc,TANuocYen,TACaCao,TANguCoc,TAMatOng,ThayDoiThoiQuen
V1,,,,,,,,,,,,,,,,,,,,,
319143,3,1,1,0,1,2,2,2,1,1,...,0,0,0,1,0,1,0,0,1,0
319147,3,0,0,1,0,2,2,2,2,1,...,2,0,1,1,0,1,0,2,0,0
319153,2,1,1,0,0,1,2,2,1,1,...,0,0,1,0,2,1,0,0,0,0
319182,2,2,0,0,0,2,1,0,1,1,...,0,<NA>,0,0,0,2,0,0,0,0
319210,3,1,0,0,0,2,2,2,<NA>,2,...,<NA>,1,0,0,0,1,0,0,0,0
319230,1,0,0,0,0,2,1,2,2,1,...,0,0,0,1,0,0,0,0,1,<NA>
519005,1,1,1,1,1,2,2,1,1,1,...,1,0,1,1,1,0,1,0,0,<NA>
519007,4,0,0,0,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,<NA>
519012,3,3,0,0,0,1,1,2,2,<NA>,...,0,1,0,1,1,1,0,1,1,<NA>
519013,3,0,1,0,0,2,2,2,2,2,...,2,1,1,1,0,0,1,0,1,<NA>
519014,3,2,1,3,0,2,1,3,2,1,...,<NA>,0,0,0,0,1,0,0,0,0
519016,3,3,1,2,1,2,2,2,2,1,...,1,1,2,1,0,1,0,1,2,0
519022,0,0,2,3,2,1,1,1,4,4,...,3,0,1,0,0,1,0,0,0,1
519024,4,0,0,0,0,3,3,3,3,0,...,1,0,0,0,0,0,0,0,0,<NA>
519025,4,2,1,0,0,2,2,2,3,2,...,1,1,0,0,0,0,2,0,0,<NA>
519029,2,3,4,1,1,1,2,2,2,2,...,1,0,2,4,0,2,4,4,4,<NA>
519031,3,2,0,0,0,<NA>,2,2,3,0,...,2,1,0,0,0,3,0,0,0,0
519045,1,0,0,0,0,1,1,2,0,1,...,0,0,0,0,1,0,0,0,0,<NA>
519046,4,4,1,0,0,3,2,2,3,1,...,1,1,0,0,0,1,0,0,0,1
519047,4,3,1,0,0,2,0,2,2,3,...,3,0,0,1,0,2,0,0,0,<NA>
519049,2,1,1,1,1,2,2,2,2,1,...,1,1,1,0,0,0,0,0,0,<NA>
519051,3,0,0,1,<NA>,2,2,3,2,2,...,0,0,0,0,0,0,0,0,2,0
519061,2,2,0,0,0,2,2,2,2,2,...,1,1,2,2,1,1,0,2,2,<NA>
519068,2,2,1,<NA>,0,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
519080,0,0,0,0,0,1,2,2,2,2,...,<NA>,0,1,1,1,2,0,0,0,0
519081,1,1,1,0,0,1,1,2,2,1,...,1,0,1,1,0,0,0,0,0,0
519086,2,1,1,2,0,<NA>,1,2,1,1,...,0,0,0,2,0,0,0,0,0,0
519089,2,0,0,0,0,1,2,2,2,1,...,1,0,1,1,0,0,<NA>,0,0,0
520018,0,0,0,0,0,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df.to_excel(inter / 'form2c.xlsx')