In [1]:
import pandas as pd
from pathlib import Path

In [2]:
ext = Path('/home/kyo/Documents/project/prd/data/external')
inter = Path('/home/kyo/Documents/project/prd/data/intermediate')
dtype = {
    'NgayTG': 'string',
    'V1': 'string',
    'Cay': 'boolean',
    'PCR': 'boolean',
    'Clo': 'boolean',
    'GPB': 'boolean',
#     'NhiemHP': 'boolean'
}
df = pd.read_csv(
    ext / 'prd_v2.0.0_Entry.csv',
    dtype=dtype,
    usecols=[*dtype])

In [3]:
df['NgayTG'] = pd.to_datetime(df['NgayTG'], format='%m-%d-%Y', errors='coerce')
df[
    (df.NgayTG.isna())
    | (df.Cay.isna())
    | (df.PCR.isna())
    | (df.Clo.isna())
    | (df.GPB.isna())
]

         V1     NgayTG    Cay   PCR   Clo    GPB
4    219005 2019-11-20   True  True  <NA>   True
6    219007 2019-12-24   True  True  <NA>   True
8    219009 2020-02-27   <NA>  <NA>  <NA>   <NA>
9    219010 2020-02-27   <NA>  <NA>  <NA>   <NA>
10   219011 2020-03-03   <NA>  <NA>  <NA>   <NA>
11   219012 2020-03-03   <NA>  <NA>  <NA>   <NA>
12   219013 2020-03-12   <NA>  <NA>  <NA>   <NA>
13   219014 2020-03-12   <NA>  <NA>  <NA>   <NA>
14   219016 2020-05-28   <NA>  <NA>  <NA>   <NA>
153  519014 2019-12-17   True  <NA>  True  False
203  520017 2020-01-07   True  True  <NA>   True
204  520018 2020-01-07   <NA>  True  <NA>   True
227  519066 2020-07-20   True  True  True   <NA>
233  519069 2020-07-27  False  True  True   <NA>
234  519070 2020-07-27  False  True  True   <NA>
305  519077 2020-08-17   True  True  True   <NA>
307  519079 2020-08-24  False  True  True   <NA>
310  519082 2020-09-07  False  True  True   <NA>
311  519083 2020-09-07  False  True  True   <NA>
315  519087 2020-10-05  False  True  True   <NA>
317  519089 2020-10-16   True  True  True   <NA>
338  319229        NaT   <NA>  <NA>  <NA>   <NA>

In [4]:
df['HP'] = df.Cay | (df.PCR & df.GPB) | (df.GPB & df.Clo)
# df['foo'] = df.HP & df.NhiemHP
# df[((df.HP == True) & (df.NhiemHP == False))]
df.set_index('V1')
# df[(df.V1 < 500000) & (df.V1 > 300000)].HP.value_counts()
df.to_excel(inter / 'entry.xlsx')